package com.smartsociety.audit.entity;

public enum AuditAction {
    LOGIN, LOGOUT, LOGOUT_ALL, REGISTER,
    PASSWORD_CHANGE, PASSWORD_RESET, FAILED_LOGIN,

    SOCIETY_CREATE, SOCIETY_UPDATE, SOCIETY_ACTIVATE,
    SOCIETY_DEACTIVATE, SOCIETY_DELETE,

    MEMBER_ADD, MEMBER_REMOVE, MEMBER_ROLE_UPDATE,

    COMPLAINT_CREATE, COMPLAINT_ASSIGN, COMPLAINT_ACCEPT,
    COMPLAINT_WORK_START, COMPLAINT_WORK_COMPLETE,
    COMPLAINT_RESOLVE, COMPLAINT_CLOSE, COMPLAINT_REOPEN,
    COMPLAINT_CANCEL, COMPLAINT_ESCALATE,

    VENDOR_REGISTER, VENDOR_APPROVE, VENDOR_UPDATE,
    VENDOR_SUSPEND, VENDOR_ACTIVATE, VENDOR_RATED,

    NOTICE_CREATE, NOTICE_UPDATE, NOTICE_PUBLISH,
    NOTICE_ARCHIVE, NOTICE_DELETE,

    DATA_EXPORT, SETTINGS_CHANGE
}