package com.smartsociety.notification.entity;

public enum NotificationType {
    COMPLAINT_CREATED,
    COMPLAINT_ASSIGNED,
    COMPLAINT_ACCEPTED,
    COMPLAINT_WORK_STARTED,
    COMPLAINT_WORK_COMPLETED,
    COMPLAINT_PENDING_VERIFICATION,
    COMPLAINT_RESOLVED,
    COMPLAINT_REOPENED,
    COMPLAINT_ESCALATED,
    COMPLAINT_CANCELLED,
    NOTICE_PUBLISHED,
    VENDOR_APPROVED,
    GENERAL
}